name: HolographicScoreboard
main: dk.lockfuglsang.wolfencraft.HolographicScoreboard
author: R4zorax
version: ${project.version}
api-version: 1.13
softdepend: [HolographicDisplays, ProtocolLib, Holograms]
load: POSTWORLD
commands:
  holographicscoreboard:
    description: §2Holographic Scoreboard §3v${project.version} §fby §4R4zorax
    usage: |
      §2Holographic Scoreboard §3v${project.version} §fby §4R4zorax
      §3/<command> §6list §7- Lists all the current scoreboards
      §3/<command> §6create §2<id> <interval> <player|console> [world:x,y,z] <cmd>
      §3/<command> §6move §2<id> [world:x,y,z] §7- Moves the board to the supplied position
      §3/<command> §6edit §2<id> <key> <value> §7- Edits a key of the score-board
      §3/<command> §6remove §2<id>
      §3/<command> §6reload §7- Reloads configuration
      §3/<command> §6save §7- Saves configuration
      §3/<command> §6refresh §2[id] §7- Refreshes scoreboards now
    aliases: hgs

permissions:
  holographicscoreboard.*:
    description: Gives access to all the Holographic Scoreboard commands
    children:
      holographicscoreboard.admin: true
  holographicscoreboard.admin:
    description: Allows the user to edit scoreboards
    default: op
